### DISCUSSION TITLE
Noob-friendly way to implement Unraid Widget on Homepage

### DISCUSSION THREAD

**Discussion by BBT-nZ** [NebN/unraid-simple-monitoring-api#35] [Q&A]
Hey Author,

As the subject states, I've my unraid server running while my homepage sits on another host. I'm sure just as myself, many community people would be keen to implement this amazing custom api for their homepage to read Unraid data. Since, homepage does not have a native widget, service yet.

Is there a simply tutorial/guide to follow where one can execute this? Would be highly appreciated.

Thanks.

**Comment by NebN** [comment]
Hey there, the [readme page](https://github.com/NebN/unraid-simple-monitoring-api/blob/master/README.md) explains the necessary steps to get everything set up properly, from installation to configuration. If something isn't clear please let me know so I can improve it.

**Comment by BBT-nZ** [comment]
Thanks for getting back to me! Really loving the widget so far—I somehow fumbled my way through and got it up and running! 😄

Now, in saying that, is there anything specific I need to do to customize the widget to look more like the image below? I’d love to have more of those square boxes to display CPU stats, HDD1, HDD2, HDD3, and so on. I've seen many people getting multiple of those boxes on the official homepage github posts.

![image](https://github.com/user-attachments/assets/f97e0f15-b285-4111-a8a2-6f8a5ca4384d)

I’m fairly new to this, so please be gentle! Also, how can one contribute to this awesome work?

**Reply by NebN** [reply]
Glad you like it.

As far as I understand, the custom API widget only allows for 4 fields to be displayed in the horizontal boxes. There are two ways of displaying more information:

- Make a second Unraid section, which will provide 4 more slots, like this
![image](https://github.com/user-attachments/assets/7a4f8126-fc6b-4716-8508-ebe09e7990cc)

- Use the `display: list` property, as described at the bottom of the [Homepage configuration section](https://github.com/NebN/unraid-simple-monitoring-api?tab=readme-ov-file#integration-with-homepage-). I will paste the example here for convenience:
```yaml
widget:
  type: customapi
  display: list
  mappings:
     ...
```
![image](https://github.com/user-attachments/assets/eea477a1-e2db-408c-9e0c-d0d0c60613b2)

---

As far as contributing goes there are no guidelines, anything is appreciated. Although it is a very simple project with a limited scope, so I'm not sure how much more room there is for it to grow any further.

**Reply by BBT-nZ** [reply]
Hey bud, once again thankyou so much for sharing your insights. Believe, I took those + mixed it with my OCD + midnight oil and somehow manage to crush the living crap out of things! Gosh, could never have felt more proud of it 👯 . Even managed to increase the stats squares I was asking about earlier! whoops

Like it? LoL - freaggin loving this. Thanks for all your hard work and dedication. Any Ko-Fi links for contribution?

![image](https://github.com/user-attachments/assets/e2b0afe9-092a-4cf2-91d7-60239fa05721)

Any feedbacks? :)

**Reply by NebN** [reply]
Nice! And looks like I was wrong, would you mind sharing how you configured the `Disk Info` section? How did you manage to get more than 4 fields without using `display: list`?

As far as donating goes, it is absolutely not necessary, but I did setup a page a while back when Unraid asked if I had one: [buymeacoffee](https://buymeacoffee.com/nebn)

**Reply by BBT-nZ** [reply]
Thanks mate! I kno right? The feeling was = unlocking some MagiCalPowers haha ;) not only x4. I even tried x4,x8,x12 at one point to figure out the logic behind it. Once, I had that figured out it was pretty straight forward to fine tweak the way I wanted it to look like. Essentially, HDD1-HDD6 for my x6 Bay Custom 10"inch PCB that i've been working on. Anyways, code below:

```
    - Unraid:
        icon: /icons/unraid.svg
        href: https://unraid.mydomain.org/
        ping: http://10.10.200.100/
        widgets:
         - type: customapi
           display: list
           url: http://10.10.200.100:24940
           method: GET # this doesn't matter
           mappings:
            - field:
                cpu: load_percent # or temp
              label: CPU
              format: percent # or number
            - field:
                memory: used_percent # or free_percent, total, used, free
              label: MEMORY
              format: percent
            - field:
                array_total: free # or used, total, used_percent, free_percent, temp, mount, disk_id, is_spinning
              label: ARRAY
              format: number
              suffix: GiB
            - field:
                cache_total: free
              label: CACHE
              format: number
              suffix: GiB
            - field:
                network_total: rx_MiBs
              label: NETWORK RX
              format: float
              suffix: MiB/s
            - field:
                network_total: tx_MiBs
              label: NETWORK TX
              format: float
              suffix: MiB/s
```

```
    - Disk Info:
        icon: /icons/unraid.svg
        href: https://unraid.mydomain.org/
        ping: http://10.10.200.100/
        widgets:
         - type: customapi
           url: http://10.10.200.100:24940
           method: GET # this doesn't matter
           mappings:   
            - field:
                array: # or cache
                    0: free
                    # '0' is the index of the disk, 0 = the first 
                    # 'free' is the field you wish to read
              label: HDD1
              format: number
              suffix: GiB
            - field:
                array: # or cache
                    1: free
                    # '0' is the index of the disk, 0 = the first 
                    # 'free' is the field you wish to read
              label: HDD2
              format: number
              suffix: GiB
            - field:
                array: # or cache
                    2: free
                    # '0' is the index of the disk, 0 = the first 
                    # 'free' is the field you wish to read
              label: HDD3
              format: number
              suffix: GiB

         - type: customapi
           url: http://10.10.200.100:24940
           method: GET # this doesn't matter
           mappings:
            - field:
                array: # or cache
                    3: free
                    # '0' is the index of the disk, 0 = the first 
                    # 'free' is the field you wish to read
              label: HDD4
              format: number
              suffix: GiB
            - field:
                array: # or cache
                    4: free
                    # '0' is the index of the disk, 0 = the first 
                    # 'free' is the field you wish to read
              label: HDD5
              format: number
              suffix: GiB
            - field:
                array: # or cache
                    5: free
                    # '0' is the index of the disk, 0 = the first 
                    # 'free' is the field you wish to read
              label: HDD6
              format: number
              suffix: GiB

         - type: customapi
           url: http://10.10.200.100:24940
           method: GET # this doesn't matter
           mappings:
            - field:
                cache: # or cache
                    0: free
                    # '0' is the index of the disk, 0 = the first 
                    # 'free' is the field you wish to read
              label: CACHE 1
              format: number
              suffix: GiB
            - field:
                cache: # or cache
                    1: free
                    # '0' is the index of the disk, 0 = the first 
                    # 'free' is the field you wish to read
              label: CACHE 2
              format: number
              suffix: GiB
         - type: customapi
           url: http://10.10.200.100:24940
           method: GET # this doesn't matter
           mappings:  
            - field:
                parity: 
                     0: temp 
                     # '0' is the index of the parity disk, 0 = the first 
                     # 'temp' is the field you wish to read
                label: PARITY
                format: number
                suffix: °

```
