### ISSUE TITLE
Feature Request: Non-array pools

### ISSUE THREAD

**Issue by cbrherms** [NebN/unraid-simple-monitoring-api#33]
Unraid 7.0 will remove the need for the "array" pool to be populated with disks, allowing people to not use the array at all and instead use unraid with multiple other pool types on their own such as zfs and btrfs pools. There are already an amount of people who have created their array with just a usb stick in it and used unraid solely with pools.

It would be useful if this api could read these pools as separate entities to the array, especially when calculating things like free space etc.

For example, I have my main array for media, plus another pool that uses zfs. It would be useful to be able to have a config such as:
```
disks:
  cache:
    - /mnt/cache
  array:
    - /mnt/disk1
    - /mnt/disk2
    - /mnt/disk3
    - /mnt/disk4
  pool1:
    - /mnt/TANK
```

Aware that at least with ZFS pools, there's just a single mount point. 
Currently i'm having to add this mount point in to the array section and just have the total rather than being able to see individual pool free space.

**Comment by NebN** [comment]
This is an interesting suggestion, I am unsure how I would format the response, though.
I will look into after the holiday season.

**Comment by NebN** [comment]
Sorry for the long wait. 

A [QA Build](https://github.com/NebN/unraid-simple-monitoring-api?tab=readme-ov-file#installing-a-qa-build-) is available. I just tested it by pretending some of my regular disks were part of a pool, could you please see if it works with your setup?

Configuration I used:

```yaml
networks:
  - docker0
  - eth0
disks:
  cache:
    - /mnt/cache
    - /mnt/applications
  array:
    - /mnt/disk1
    - /mnt/disk2
    - /mnt/disk5
    - /mnt/disk6
    - /mnt/disk7
  odd:
    - /mnt/disk1
    - /mnt/disk5
  even:
    - /mnt/disk2
    - /mnt/disk6
```

Response:
```json
  "array": [...],
  "cache": [...],
  "pools": [
    {
      "name": "odd",
      "total": {
        "mount": "/mnt/disk*",
        "total": 6517,
        "used": 5478,
        "free": 1039,
        "used_percent": 84.06,
        "free_percent": 15.94,
        "temp": 0,
        "disk_id": "...",
        "is_spinning": false
      },
      "disks": [
        {
          "mount": "/mnt/disk1",
          "total": 3724,
          "used": 3262,
          "free": 462,
          "used_percent": 87.59,
          "free_percent": 12.41,
          "temp": 0,
          "disk_id": "...",
          "is_spinning": false
        },
        {
          "mount": "/mnt/disk5",
          "total": 2793,
          "used": 2216,
          "free": 577,
          "used_percent": 79.34,
          "free_percent": 20.66,
          "temp": 0,
          "disk_id": "...",
          "is_spinning": false
        }
      ]
    },
    {
      "name": "even",
      "total": {
        "mount": "/mnt/disk*",
        "total": 5586,
        "used": 4175,
        "free": 1411,
        "used_percent": 74.74,
        "free_percent": 25.26,
        "temp": 0,
        "disk_id": "...",
        "is_spinning": false
      },
      "disks": [
        {
          "mount": "/mnt/disk2",
          "total": 3724,
          "used": 3240,
          "free": 484,
          "used_percent": 87,
          "free_percent": 13,
          "temp": 0,
          "disk_id": "...",
          "is_spinning": false
        },
        {
          "mount": "/mnt/disk6",
          "total": 1862,
          "used": 935,
          "free": 927,
          "used_percent": 50.21,
          "free_percent": 49.79,
          "temp": 0,
          "disk_id": "...",
          "is_spinning": false
        }
      ]
    }
  ], ...
```

**Comment by the1ts** [comment]
Excellent, I can confirm, I have unraid 7 with 3 zfs pools working as expected with this qa build. I now have a homepage card with all three showing in my list of items.

**Comment by cbrherms** [comment]
@NebN No worries. Appreciate you looking in to it!

Ran a test with the following config:

```yaml
networks:
  - eth0
disks:
  cache:
    - /mnt/cache
  array:
    - /mnt/disk1
    - /mnt/disk2
    - /mnt/disk3
    - /mnt/disk4
    - /mnt/disk5
    - /mnt/disk6
    - /mnt/disk7
    - /mnt/disk8
    - /mnt/disk9
    - /mnt/disk10
    - /mnt/disk11
    - /mnt/disk12
    - /mnt/disk13
    - /mnt/disk14
    - /mnt/disk15
    - /mnt/disk16
  tank:    
    - /mnt/tank
LoggingLevel: DEBUG
```

And the response was as follows:

```json
{
    "array": [...],
    "cache": [...],
    "pools": [
      {
        "name": "tank",
        "total": {
          "mount": "/mnt/tank*",
          "total": 29808,
          "used": 23180,
          "free": 6628,
          "used_percent": 77.76,
          "free_percent": 22.24,
          "temp": 33,
          "disk_id": "...SERIAL_OF_FIRST_DRIVE_IN_BTRFS_POOL...",
          "is_spinning": true
        },
        "disks": [
          {
            "mount": "/mnt/tank",
            "total": 29808,
            "used": 23180,
            "free": 6628,
            "used_percent": 77.76,
            "free_percent": 22.24,
            "temp": 33,
            "disk_id": "...SERIAL_OF_FIRST_DRIVE_IN_BTRFS_POOL...",
            "is_spinning": true
          }
        ]
      }
    ],
    "parity": [...],
    "network": [...],
    "array_total": {
      "mount": "/mnt/disk*",
      "total": 89392,
      "used": 41874,
      "free": 47518,
      "used_percent": 46.84,
      "free_percent": 53.16,
      "temp": 34,
      "disk_id": "...",
      "is_spinning": true
    },
    "cache_total": {
      "mount": "/mnt/cache*",
      "total": 931,
      "used": 69,
      "free": 862,
      "used_percent": 7.41,
      "free_percent": 92.59,
      "temp": 30,
      "disk_id": "...",
      "is_spinning": true
    },
    "network_total": {...},
    "cpu": {...},
    "cores": [...],
    "memory": {...},
    "error": null
  }
```

Believe these kind of pools would only have the one mount point in `/mnt`, so i'm not sure if they would need a disks section?
In my case, there would only be one entry under the disks key (though the pool consists of 6). The `disk_id` field in both `total` and `disks` had the serial for a single drive in the pool. Unless it's possible to find all serials in that pool i'm not sure if that's needed?

Just so you can see my /mnt directory structure:

```
/mnt
├── addons
├── cache
├── disk1
├── disk10
├── disk11
├── disk12
├── disk13
├── disk14
├── disk15
├── disk16
├── disk2
├── disk3
├── disk4
├── disk5
├── disk6
├── disk7
├── disk8
├── disk9
├── disks
├── remotes
├── rootshare
├── tank
├── user
└── user0
```


As it stands, believe it could integrate with homepage with a similar config to the following:

##### Specific Pool
```yaml
- field:
    pools:
      0:
        total: free
      # '0' is the index of the pool, 0 = the first 
      # 'free' is the field you wish to read
  label: your label
  format: number
  suffix: GiB
```
