### ISSUE TITLE
Feature Request: CORS support

### ISSUE THREAD

**Issue by yasheena** [NebN/unraid-simple-monitoring-api#34]
Is it possible to add CORS support by adding the data

       "Access-Control-Allow-Origin"
       "Access-Control-Allow-Methods"
       "Access-Control-Allow-Headers"

to the response header, if there are values defined for them in the conf.yml?

**Comment by NebN** [comment]
I don't see why not. I'll let you know once a testable build is available.

**Comment by NebN** [comment]
@yasheena [QA Build](https://github.com/NebN/unraid-simple-monitoring-api?tab=readme-ov-file#installing-a-qa-build-) is available if you could check that it behaves as you need it to.

Configuration should to look like this:

```yaml
cors:
  origin: "*"
  methods: "GET, POST, PUT"
  headers: "Content-Type, Authorization"
```
